#!/bin/bash
# Filename: brightness
# Date: 
# Author: Sauro Mayaka
# Version: 1.0
# Description: Adjust screen brightness
# Options: None

#Usage: brightness [ value i.e 34 range{0-100} ]

# Function to display loading animation
loading() {
    message=$1
    tput civis
    trap "tput cnorm; exit" INT TERM EXIT
    printf "%s" "$message"
    sleep .5
    for i in {1..3}; do
        printf "."
        sleep 1
    done
    sleep .5
    tput cnorm
    printf "\n"
}

# Main script logic
if [ $# -ne 1 ] ; then
	echo "Usage: brightness [value i.e 34 range {0-100} ]"
	exit 1
else
	brightness_value="$1%"
	if [[ $1 =~ ^([0-9]|[1-9][0-9]|100)$ ]]; then
		loading "Adjusting brightness"

		brightnessctl s $brightness_value
		printf "[+] Brightness Level has been set to : %s\n" $brightness_value
		exit 0
	else
		printf "Invalid Brightness value.\n"
		echo -e "Usage: \e[1;35m brightness [ value. i.e 1-100 ]\e[1;0m"
		exit 1
	fi
fi
