#!/bin/bash
#: Filename: lints
#: Date: 2026-04-06/13:06:25
#: Author: Sauro 
#: Version: 1.0
#: Description: Display all the IP addresses of interfaces.
#: Options: 


# interfaces_string=`ip a | grep state | cut -d ':' -f 2 | sed 's/^ *//' | tr '\n' ':'`
interfaces_string=`ip a | egrep '^[0-9]:' | tr -d ' ' | cut -d ':' -f 2 | tr '\n' ' '`

number_of_interfaces=`ip a | egrep '^[0-9]:' | wc -l`
interfaces_array=($interfaces_string)


ip_regex_pattern='((([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]))'
# ips_string=`ip a | grep inet | egrep \([0-9][0-9]?[0-9]?\)\.\([0-9][0-9]?[0-9]?\)\.\([0-9][0-9]?[0-9]?\)\.\([0-9][0-9]?[0-9]?\) | sed 's/^ *//' | cut -d ' ' -f 2 | cut -d '/' -f 1 | tr "\n" ":"`

ip_string=`ip a | egrep "$ip_regex_pattern" | cut -d / -f 1 | rev | cut -d ' ' -f 1 | rev | tr '\n' ' '`

ips_array=($ip_string)

heading_pattern="\e[1;44m\e[1;37m%s %-10s %-15s\e[0m\n"
interface_pattern="%d.  %-10s %-15s\n"
printf "$heading_pattern" No. Interface 'Ip Address'

for interface_index in ${!interfaces_array[@]}; do
    let index=interface_index+1
    printf "$interface_pattern" $index ${interfaces_array[$interface_index]} ${ips_array[$interface_index]}

done



